// src/components/ui/label.tsx
"use client";

import * as React from "react";
import * as LabelPrimitive from "@radix-ui/react-label@2.1.2";

import { cn } from "./utils";

function Label({
  className,
  ...props
}: React.ComponentProps<typeof LabelPrimitive.Root>) {
  return (
    <LabelPrimitive.Root
      data-slot="label"
      className={cn(
        "flex items-center gap-2 text-xs leading-none text-gray-500 select-none group-data-[disabled=true]:pointer-events-none group-data-[disabled=true]:opacity-50 peer-disabled:cursor-not-allowed peer-disabled:opacity-50 my-2",
        className,
      )}
      {...props}
    />
  );
}

export { Label };

// src/components/ui/Label.svelte
<script lang="ts">
  import { Label as LabelPrimitive, type WithoutChildrenOrChild } from "bits-ui";
  import { cn } from "@/lib/utils";

  type Props = WithoutChildrenOrChild<LabelPrimitive.RootProps> & {
    class?: string;
    children?: import("svelte").Snippet;
  };

  let { class: className, children, ...rest }: Props = $props();
</script>

<LabelPrimitive.Root
  class={cn(
    "flex items-center gap-2 text-xs leading-none text-gray-500 select-none group-data-[disabled=true]:pointer-events-none group-data-[disabled=true]:opacity-50 peer-disabled:cursor-not-allowed peer-disabled:opacity-50 my-2",
    className
  )}
  {...rest}
>
  {@render children?.()}
</LabelPrimitive.Root>
